with Ada.Strings; use Ada.Strings;
with Ada.Strings.Maps;
with Ada.Strings.Fixed; use Ada.Strings.Fixed;
with Ada.Text_IO;
procedure FixedStrings is
    procedure check (condition : Boolean; message : String) is
    begin
        if not condition then
            Ada.Text_IO.Put_Line (message);
            raise Program_Error;
        end if;
    end check;
    s : String (5 .. 11) := " ababa ";
    t : String (8 .. 12) := "abcde";
    empty : String (7 .. 6) := "";
    edge : String (Integer'Last - 2 .. Integer'Last) := "aba";
    letters : Ada.Strings.Maps.Character_Set := Ada.Strings.Maps.To_Set ("ab");
    mapping : Ada.Strings.Maps.Character_Mapping := Ada.Strings.Maps.To_Mapping ("AB", "ab");
    first : Positive;
    last : Natural;
begin
    check (Index (s, "aba") = 6 and Index (s, "aba", Backward) = 8, "search directions");
    check (Index (s, "aba", From => 9, Going => Backward) = 6, "backward From is upper bound");
    check (Index (s, "aba", From => 7) = 8, "forward From");
    check (Index (s, "long pattern") = 0 and Index (empty, "x", Backward) = 0, "no match");
    check (Index ("ABA", "aba", Mapping => mapping) = 1, "source mapping");
    check (Index ("aba", "ABA", Mapping => mapping) = 0, "pattern is not mapped");
    check (Index (s, letters) = 6 and Index (s, letters, Going => Backward) = 10, "set search");
    check (Index (s, letters, Test => Outside) = 5, "complement search");
    check (Index_Non_Blank (s) = 6 and Index_Non_Blank (s, 9, Backward) = 9, "nonblank");
    check (Count ("aaaaa", "aa") = 2 and Count (s, letters) = 5, "counts");
    Find_Token (s, letters, Inside, first, last);
    check (first = 6 and last = 10, "token");
    Find_Token (s, letters, 8, Inside, first, last);
    check (first = 8 and last = 10, "token From");
    Find_Token (empty, letters, 99, Inside, first, last);
    check (first = 99 and last = 0, "empty token");
    Find_Token ("  ", letters, Inside, first, last);
    check (first = 1 and last = 0, "missing token");
    check (Translate ("AB!", mapping) = "ab!", "translation");
    t := "ABABA";
    Translate (t, mapping);
    check (t = "ababa", "in-place translation");
    check (Trim (s, Both) = "ababa", "trim and rebase");
    check (Trim ("abbaXba", letters, letters) = "X", "trim sets");
    check (Trim ("   ", Both) = "" and Trim (empty, Both) = "", "empty trim");
    check (Head (s, 3) = " ab" and Tail (s, 3) = "ba ", "head and tail");
    check (Head ("ab", 4, '.') = "ab.." and Tail ("ab", 4, '.') = "..ab", "padding");
    check (3 * 'x' = "xxx" and 3 * "ab" = "ababab" and 0 * "ab" = "", "replication");
    check (Integer'Last * "" = "", "empty repetition");
    check (Insert (s, 6, "X") = " Xababa ", "insert");
    check (Replace_Slice (s, 6, 8, "X") = " Xba ", "replace");
    check (Replace_Slice (s, 1, 99, "X") = "X", "replacement beyond both ends");
    check (Replace_Slice (s, 6, 5, "X") = Insert (s, 6, "X"), "null replacement");
    check (Overwrite (s, 10, "XYZ") = " ababXYZ", "overwrite extension");
    check (Overwrite (s, 8, "") = s and Overwrite (s, 7, "X") = " aXaba ", "overwrite bounds");
    check (Delete (s, 6, 8) = " ba " and Delete (s, 99, 0) = s, "delete");
    Move ("ab", t, Justify => Center, Pad => '.');
    check (t = ".ab..", "center padding");
    Move ("abcdef", t, Drop => Left);
    check (t = "bcdef", "drop left");
    Move ("abcdef", t, Drop => Right);
    check (t = "abcde", "drop right");
    Move ("abcde  ", t);
    check (t = "abcde", "discard trailing pad");
    Move ("  abcde", t, Justify => Right);
    check (t = "abcde", "discard leading pad");
    Move (t (8 .. 11), t, Justify => Right);
    check (t = " abcd", "overlapping move");
    t := "abcde";
    Insert (t, 10, t (8 .. 9), Drop => Right);
    check (t = "ababc", "overlapping insert");
    Replace_Slice (t, 8, 9, "X", Pad => '.');
    check (t = "Xabc.", "replace procedure");
    Overwrite (t, 11, "XYZ");
    check (t = "XabXY", "overwrite procedure default truncation");
    Delete (t, 8, 9, Justify => Right, Pad => '.');
    check (t = "..bXY", "delete procedure");
    t := " ab  ";
    Trim (t, Both, Justify => Center, Pad => '.');
    check (t = ".ab..", "trim procedure");
    Trim (t, Ada.Strings.Maps.To_Set ('.'), Ada.Strings.Maps.To_Set ('.'));
    check (t = "ab   ", "trim sets procedure");
    Head (t, 2, Justify => Right, Pad => '.');
    check (t = "...ab", "head procedure");
    Tail (t, 2, Pad => '.');
    check (t = "ab...", "tail procedure");
    check (Index (edge, "ba", Backward) = Integer'Last - 1, "maximum-bound search");
    check (Trim (edge, Both) = "aba" and Translate (edge, mapping) = "aba", "maximum-bound results");
    check (Replace_Slice (edge, Integer'Last, Integer'Last, "X") = "abX", "maximum-bound replace");
    check (Overwrite (edge, Integer'Last, "X") = "abX", "maximum-bound overwrite");
    declare
        trimmed : String := Trim (s, Both);
        headed : String := Head (empty, 0);
        translated : String := Translate (empty, mapping);
    begin
        check (trimmed'First = 1 and headed'First = 1 and translated'First = 1, "result bounds");
    end;
    Ada.Text_IO.Put_Line ("fixedstrings: passed");
end FixedStrings;
