# Exercise dependency changes and bind failures through the public commands.
set(work "${WORKDIR}/separate-${CASE}")
file(REMOVE_RECURSE "${work}")
file(MAKE_DIRECTORY "${work}/lib" "${work}/app")
file(COPY "${FIXTURES}/" DESTINATION "${work}")
set(program "${work}/program${CMAKE_EXECUTABLE_SUFFIX}")
set(objects "${work}/objects")
set(main "${work}/review_main.adb")

function(run)
    execute_process(COMMAND ${ARGV} RESULT_VARIABLE status
        OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Command failed: ${ARGV}\n${status}\n${output}${errors}")
    endif()
    set(commands "${output}${errors}" PARENT_SCOPE)
endfunction()

function(expect_output expected)
    run("${program}")
    if(NOT commands STREQUAL "${expected}\n")
        message(FATAL_ERROR "Expected '${expected}', got '${commands}'")
    endif()
endfunction()

function(reject_binding unit expected)
    execute_process(COMMAND "${ADAC}" --bind "${unit}" -D "${objects}"
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
    if(status EQUAL 0 OR NOT errors MATCHES "${expected}")
        message(FATAL_ERROR "Expected bind rejection '${expected}': ${status}\n${output}${errors}")
    endif()
endfunction()

macro(build)
    run("${ADA}" -v -D "${objects}" -o "${program}" ${sources})
endmacro()

if(CASE STREQUAL "order")
    set(sources "${work}/order_main.adb")
    build()
    expect_output(" 42")
elseif(CASE STREQUAL "paths")
    # Sources explicitly provided from distinct directories must stay visible
    # to every per-unit invocation, including paths containing spaces.
    file(MAKE_DIRECTORY "${work}/library files")
    file(RENAME "${work}/order_a.ads" "${work}/library files/order_a.ads")
    file(RENAME "${work}/order_b.ads" "${work}/app/order_b.ads")
    file(RENAME "${work}/order_main.adb" "${work}/app/order_main.adb")
    set(sources "${work}/library files/order_a.ads" "${work}/app/order_main.adb")
    build()
    expect_output(" 42")
else()
    set(sources "${main}")
    build()
    expect_output(" 1")
    if(CASE STREQUAL "generic")
        file(READ "${work}/review_generic.adb" body)
        string(REPLACE "return 1" "return 2" body "${body}")
        file(WRITE "${work}/review_generic.adb" "${body}")
        build()
        expect_output(" 2")
        build()
        if(commands MATCHES " -c ")
            message(FATAL_ERROR "Unchanged build recompiled a unit: ${commands}")
        endif()
    elseif(CASE STREQUAL "compiler")
        # Model records produced by a different front-end binary. The driver
        # must regenerate them, even with identical source and IR contents.
        file(GLOB records "${objects}/*.ali")
        foreach(record IN LISTS records)
            file(READ "${record}" text)
            string(REGEX REPLACE "compiler [^\n]+" "compiler old-compiler" text "${text}")
            file(WRITE "${record}" "${text}")
        endforeach()
        reject_binding(review_main "stale compiled unit")
        build()
        if(NOT commands MATCHES " -c ")
            message(FATAL_ERROR "Compiler change did not recompile: ${commands}")
        endif()
        expect_output(" 1")
    elseif(CASE STREQUAL "binding")
        reject_binding(nonexistent "no main subprogram")
        reject_binding(review_generic "no main subprogram")
        file(READ "${objects}/review_generic.ali" record)
        file(REMOVE "${objects}/review_generic.ali")
        reject_binding(review_main "stale compiled unit")
        file(WRITE "${objects}/review_generic.ali" "${record}")
        file(APPEND "${objects}/review_main.ssa" "# modified IR\n")
        reject_binding(review_main "stale compiled unit")
        build()
        file(READ "${work}/review_generic.adb" body)
        string(REPLACE "return 1" "return 2" body "${body}")
        file(WRITE "${work}/review_generic.adb" "${body}")
        run("${ADAC}" --scan -D "${objects}" "${main}")
        # Recompile only the generic, leaving its instantiator stale.
        run("${ADAC}" -c -D "${objects}" "${work}/review_generic.adb")
        reject_binding(review_main "stale compiled unit 'review_main'")
    else()
        message(FATAL_ERROR "Unknown CASE: ${CASE}")
    endif()
endif()
