file(MAKE_DIRECTORY "${WORKDIR}")
set(program "${WORKDIR}/basepower")
execute_process(COMMAND "${ADA}" -S -o "${program}.s" "${SOURCE}"
    RESULT_VARIABLE status)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Base and power compilation failed")
endif()
set(math_library)
if(SEPARATE_LIBM)
    set(math_library -lm)
endif()
execute_process(COMMAND "${CC}" -pthread "${program}.s" "${RUNTIME}" ${math_library} -o "${program}"
    RESULT_VARIABLE status)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Base and power link failed")
endif()
execute_process(COMMAND "${program}" RESULT_VARIABLE status OUTPUT_VARIABLE output)
file(READ "${EXPECTED}" expected_output)
if(NOT status EQUAL 0 OR NOT output STREQUAL expected_output)
    message(FATAL_ERROR "Base and power regression failed: ${status}: ${output}")
endif()
