file(MAKE_DIRECTORY "${WORKDIR}")
set(program "${WORKDIR}/generatedcontexts")
execute_process(COMMAND "${ADA}" --emit-ir -o "${program}.ssa" "${SOURCE}"
    RESULT_VARIABLE status)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Generated context IR generation failed")
endif()
file(READ "${program}.ssa" ir)
if(ir MATCHES "[$]__ada_main_context" OR ir MATCHES "loadl [$]__ada_exception"
    OR ir MATCHES "call [$]__ada_trace_location" OR ir MATCHES "thread [$]")
    message(FATAL_ERROR "Generated code bypasses cached context/frame access")
endif()
string(REGEX MATCHALL "function [^\n]+[{]" functions "${ir}")
string(REGEX MATCHALL "[.]taskContext =l call [$]__ada_(trace_enter|task_context)[(]" fetches "${ir}")
list(LENGTH functions function_count)
list(LENGTH fetches fetch_count)
if(NOT function_count EQUAL fetch_count OR function_count LESS 2)
    message(FATAL_ERROR "Expected one context fetch per generated function")
endif()
execute_process(COMMAND "${ADA}" -S -o "${program}.s" "${SOURCE}"
    RESULT_VARIABLE status)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Generated context assembly generation failed")
endif()
set(math_library)
if(SEPARATE_LIBM)
    set(math_library -lm)
endif()
execute_process(COMMAND "${CC}" -std=c11 -pthread "${program}.s" "${HELPERS}" "${RUNTIME}"
    ${math_library} -o "${program}" RESULT_VARIABLE status)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Generated context link failed")
endif()
execute_process(COMMAND "${program}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT status EQUAL 0 OR NOT output STREQUAL "generated contexts ok\n")
    message(FATAL_ERROR "Generated context check failed: ${status}: ${output}${errors}")
endif()
