file(MAKE_DIRECTORY "${WORKDIR}")
set(program "${WORKDIR}/${NAME}")
execute_process(COMMAND "${ADA}" -S -o "${program}.s" "${SOURCE}"
    RESULT_VARIABLE status)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Master hook assembly generation failed")
endif()
set(extra)
if(SEPARATE_LIBM)
    list(APPEND extra -lm)
endif()
if(EXPECT_FAILURE)
    list(APPEND extra -DEXPECT_FAILURE)
endif()
if(NAME STREQUAL "masterlibraryfailure")
    list(APPEND extra -DEXPECT_LIBRARY_FAILURE)
endif()
execute_process(COMMAND "${CC}" -std=c11 -pthread "${program}.s" "${HELPERS}" "${RUNTIME}"
    ${extra} -o "${program}" RESULT_VARIABLE status)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Master hook link failed")
endif()
execute_process(COMMAND "${program}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT status EQUAL EXPECT_STATUS OR NOT output STREQUAL "master hooks ok\n")
    message(FATAL_ERROR "Master hook check failed: ${status}: ${output}${errors}")
endif()
if(EXPECT_FAILURE AND NOT errors MATCHES "CONSTRAINT_ERROR : elaboration failure")
    message(FATAL_ERROR "Pending exception was not preserved: ${errors}")
endif()
