file(MAKE_DIRECTORY "${WORKDIR}")
set(program "${WORKDIR}/numerics${BITS}")
execute_process(COMMAND "${ADA}" -S -o "${program}.s" "${SOURCE}"
    RESULT_VARIABLE status)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Numerics${BITS} compilation failed")
endif()
# QBE must remove the unselected static branch. Verify its C symbols and
# conversion instructions are absent from the generated machine assembly.
file(READ "${program}.s" assembly)
string(REGEX MATCHALL "__ada_numerics_[A-Za-z0-9_]+" mappings "${assembly}")
if(NOT mappings)
    message(FATAL_ERROR "Numerics${BITS} assembly contains no numerics calls")
endif()
foreach(mapping IN LISTS mappings)
    if(BITS EQUAL 32 AND NOT mapping MATCHES "_f32$")
        message(FATAL_ERROR "Float32 assembly selects double mapping ${mapping}")
    elseif(BITS EQUAL 64 AND mapping MATCHES "_f32$")
        message(FATAL_ERROR "Float64 assembly selects float32 mapping ${mapping}")
    endif()
endforeach()
# Cover x86 and AArch64 spellings of cross-precision conversion instructions.
if(assembly MATCHES "cvtss2sd|cvtsd2ss|fcvt[ \t]+[sd][0-9]+,[ \t]*[sd][0-9]+")
    message(FATAL_ERROR "Numerics${BITS} performs cross-precision casts")
endif()
set(math_library)
if(SEPARATE_LIBM)
    set(math_library -lm)
endif()
execute_process(COMMAND "${CC}" -pthread "${program}.s" "${RUNTIME}" ${math_library} -o "${program}"
    RESULT_VARIABLE status)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Numerics${BITS} link failed")
endif()
execute_process(COMMAND "${program}" RESULT_VARIABLE status OUTPUT_VARIABLE output)
file(READ "${EXPECTED}" expected_output)
if(NOT status EQUAL 0 OR NOT output STREQUAL expected_output)
    message(FATAL_ERROR "Numerics${BITS} regression failed: ${status}: ${output}")
endif()
