file(MAKE_DIRECTORY "${WORKDIR}")
set(program "${WORKDIR}/taggedlayout")
execute_process(COMMAND "${ADA}" -S -o "${program}.s" "${SOURCE}"
    RESULT_VARIABLE status)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Tagged layout assembly generation failed")
endif()
set(math_library)
if(SEPARATE_LIBM)
    set(math_library -lm)
endif()
execute_process(COMMAND "${CC}" -pthread "${program}.s" "${HELPERS}" "${RUNTIME}" ${math_library} -o "${program}"
    RESULT_VARIABLE status)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Tagged layout link failed")
endif()
execute_process(COMMAND "${program}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT status EQUAL 0 OR NOT output STREQUAL "tagged layout ok\n")
    message(FATAL_ERROR "Tagged layout check failed: ${status}: ${output}${errors}")
endif()
