/* Included for private declarations and public wrappers. Last two arguments:
   handle to pin (NULL for getters), and whether Impl changes shared tables. */
ADA_IO_VALUE(AdaFileRef, __ada_standard_input, (void), (), NULL, 1)
ADA_IO_VALUE(AdaFileRef, __ada_standard_output, (void), (), NULL, 1)
ADA_IO_VALUE(AdaFileRef, __ada_standard_error, (void), (), NULL, 1)
ADA_IO_VALUE(AdaFileRef, __ada_current_input, (void), (), NULL, 1)
ADA_IO_VALUE(AdaFileRef, __ada_current_output, (void), (), NULL, 1)
ADA_IO_VOID(__ada_set_input, (AdaFileRef handle), (handle), handle, 1)
ADA_IO_VOID(__ada_set_output, (AdaFileRef handle), (handle), handle, 1)
ADA_IO_VOID(__ada_file_open, (AdaFileRef handle, int mode, const char* name, int length, int create), (handle, mode, name, length, create), handle, 1)
ADA_IO_VOID(__ada_file_close, (AdaFileRef handle), (handle), handle, 1)
ADA_IO_VOID(__ada_file_delete, (AdaFileRef handle), (handle), handle, 1)
ADA_IO_VOID(__ada_file_reset, (AdaFileRef handle, int mode), (handle, mode), handle, 1)
ADA_IO_VOID(__ada_file_reset_same, (AdaFileRef handle), (handle), handle, 1)
ADA_IO_VALUE(int, __ada_file_is_open, (AdaFileRef handle), (handle), handle, 0)
ADA_IO_VALUE(int, __ada_file_mode, (AdaFileRef handle), (handle), handle, 0)
ADA_IO_VOID(__ada_file_name, (void* descriptor, AdaFileRef handle), (descriptor, handle), handle, 0)
ADA_IO_VALUE(const char*, __ada_file_form, (AdaFileRef handle), (handle), handle, 0)
ADA_IO_VALUE(int, __ada_file_end_of_file, (AdaFileRef handle), (handle), handle, 0)
ADA_IO_VOID(__ada_create, (AdaFileRef handle, int mode, const char* name, int length, const char* form, int formLength), (handle, mode, name, length, form, formLength), handle, 1)
ADA_IO_VOID(__ada_open, (AdaFileRef handle, int mode, const char* name, int length, const char* form, int formLength), (handle, mode, name, length, form, formLength), handle, 1)
ADA_IO_VOID(__ada_text_put, (AdaFileRef handle, const char* item, int length), (handle, item, length), handle, 0)
ADA_IO_VOID(__ada_text_put_line, (AdaFileRef handle, const char* item, int length), (handle, item, length), handle, 0)
ADA_IO_VOID(__ada_text_put_character, (AdaFileRef handle, int item), (handle, item), handle, 0)
ADA_IO_VOID(__ada_text_put_integer, (AdaFileRef handle, int item, int width, int base), (handle, item, width, base), handle, 0)
ADA_IO_VOID(__ada_text_put_float, (AdaFileRef handle, double item, int fore, int aft, int exponent), (handle, item, fore, aft, exponent), handle, 0)
ADA_IO_VOID(__ada_text_new_line, (AdaFileRef handle, int spacing), (handle, spacing), handle, 0)
ADA_IO_VOID(__ada_text_skip_line, (AdaFileRef handle, int spacing), (handle, spacing), handle, 0)
ADA_IO_VALUE(int, __ada_text_end_of_line, (AdaFileRef handle), (handle), handle, 0)
ADA_IO_VOID(__ada_text_get, (AdaFileRef handle, char* item), (handle, item), handle, 0)
ADA_IO_VOID(__ada_text_get_line, (AdaFileRef handle, char* item, int length, int* last), (handle, item, length, last), handle, 0)
ADA_IO_VOID(__ada_text_get_integer, (AdaFileRef handle, void* item, int size, int low, int high), (handle, item, size, low, high), handle, 0)
ADA_IO_VOID(__ada_text_get_word, (AdaFileRef handle, char* item, int length, int* last), (handle, item, length, last), handle, 0)
ADA_IO_VOID(__ada_get_word, (char* item, int length, int* last), (item, length, last), &currentInputHandle, 0)
ADA_IO_VOID(__ada_text_get_float, (AdaFileRef handle, void* item, int size), (handle, item, size), handle, 0)
ADA_IO_VOID(__ada_text_put_enum, (AdaFileRef handle, int item, int width, int set, const char** names, int count), (handle, item, width, set, names, count), handle, 0)
ADA_IO_VOID(__ada_text_get_enum, (AdaFileRef handle, void* item, int size, const char** names, int count), (handle, item, size, names, count), handle, 0)
ADA_IO_VOID(__ada_put, (const char* item, int length), (item, length), &currentOutputHandle, 0)
ADA_IO_VOID(__ada_put_line, (const char* item, int length), (item, length), &currentOutputHandle, 0)
ADA_IO_VOID(__ada_put_character, (int item), (item), &currentOutputHandle, 0)
ADA_IO_VOID(__ada_put_integer, (int item, int width, int base), (item, width, base), &currentOutputHandle, 0)
ADA_IO_VOID(__ada_new_line, (int spacing), (spacing), &currentOutputHandle, 0)
ADA_IO_VOID(__ada_skip_line, (int spacing), (spacing), &currentInputHandle, 0)
ADA_IO_VALUE(int, __ada_end_of_file, (void), (), &currentInputHandle, 0)
ADA_IO_VALUE(int, __ada_end_of_line, (void), (), &currentInputHandle, 0)
ADA_IO_VOID(__ada_get, (char* item), (item), &currentInputHandle, 0)
ADA_IO_VOID(__ada_get_line, (char* item, int length, int* last), (item, length, last), &currentInputHandle, 0)
ADA_IO_VOID(__ada_get_integer, (void* item, int size, int low, int high), (item, size, low, high), &currentInputHandle, 0)
ADA_IO_VOID(__ada_get_float, (void* item, int size), (item, size), &currentInputHandle, 0)
ADA_IO_VOID(__ada_put_enum, (int item, int width, int set, const char** names, int count), (item, width, set, names, count), &currentOutputHandle, 0)
ADA_IO_VOID(__ada_get_enum, (void* item, int size, const char** names, int count), (item, size, names, count), &currentInputHandle, 0)
ADA_IO_VOID(__ada_read_element, (AdaFileRef handle, void* item, int size), (handle, item, size), handle, 0)
ADA_IO_VOID(__ada_write_element, (AdaFileRef handle, const void* item, int size), (handle, item, size), handle, 0)
ADA_IO_VOID(__ada_direct_create, (AdaFileRef handle, int mode, const char* name, int length, const char* form,
                         int formLength), (handle, mode, name, length, form, formLength), handle, 1)
ADA_IO_VOID(__ada_direct_open, (AdaFileRef handle, int mode, const char* name, int length, const char* form, int formLength), (handle, mode, name, length, form, formLength), handle, 1)
ADA_IO_VOID(__ada_direct_reset, (AdaFileRef handle, int mode), (handle, mode), handle, 1)
ADA_IO_VOID(__ada_direct_reset_same, (AdaFileRef handle), (handle), handle, 1)
ADA_IO_VALUE(int, __ada_direct_mode, (AdaFileRef handle), (handle), handle, 0)
ADA_IO_VOID(__ada_direct_read_at, (AdaFileRef handle, void* item, int size, int index), (handle, item, size, index), handle, 0)
ADA_IO_VOID(__ada_direct_write_at, (AdaFileRef handle, const void* item, int size, int index), (handle, item, size, index), handle, 0)
ADA_IO_VOID(__ada_direct_set_index, (AdaFileRef handle, int index, int size), (handle, index, size), handle, 0)
ADA_IO_VALUE(int, __ada_direct_index, (AdaFileRef handle, int size), (handle, size), handle, 0)
ADA_IO_VALUE(int, __ada_direct_size, (AdaFileRef handle, int size), (handle, size), handle, 0)
ADA_IO_VALUE(AdaFile*, __ada_stream_of, (AdaFileRef handle), (handle), handle, 0)
ADA_IO_VOID(__ada_stream_read, (AdaFile* stream, void* item, int size), (stream, item, size), &stream, 0)
ADA_IO_VOID(__ada_stream_write, (AdaFile* stream, const void* item, int size), (stream, item, size), &stream, 0)
ADA_IO_VOID(__ada_stream_write_bounds, (AdaFile* stream, int first, int last), (stream, first, last), &stream, 0)
ADA_IO_VOID(__ada_stream_read_array, (void* descriptor, AdaFile* stream, int elementSize), (descriptor, stream, elementSize), &stream, 0)
ADA_IO_VOID(__ada_stream_elements_read, (AdaFileRef handle, void* item, int length, int first, int* last), (handle, item, length, first, last), handle, 0)
ADA_IO_VOID(__ada_stream_elements_write, (AdaFileRef handle, const void* item, int length), (handle, item, length), handle, 0)
ADA_IO_VOID(__ada_stream_set_index, (AdaFileRef handle, int index), (handle, index), handle, 0)
ADA_IO_VALUE(int, __ada_stream_index, (AdaFileRef handle), (handle), handle, 0)
ADA_IO_VALUE(int, __ada_stream_size, (AdaFileRef handle), (handle), handle, 0)
