#include "Token.h"

const char* tokenKindName(TokenKind kind)
{
    switch (kind) {
    case TokenKind::EndOfFile: return "end of file";
    case TokenKind::Identifier: return "identifier";
    case TokenKind::IntegerLiteral: return "integer literal";
    case TokenKind::RealLiteral: return "real literal";
    case TokenKind::CharacterLiteral: return "character literal";
    case TokenKind::StringLiteral: return "string literal";
    case TokenKind::KwAbort: return "abort";
    case TokenKind::KwAbs: return "abs";
    case TokenKind::KwAccept: return "accept";
    case TokenKind::KwAccess: return "access";
    case TokenKind::KwAll: return "all";
    case TokenKind::KwAnd: return "and";
    case TokenKind::KwArray: return "array";
    case TokenKind::KwAt: return "at";
    case TokenKind::KwBegin: return "begin";
    case TokenKind::KwBody: return "body";
    case TokenKind::KwCase: return "case";
    case TokenKind::KwConstant: return "constant";
    case TokenKind::KwDeclare: return "declare";
    case TokenKind::KwDelay: return "delay";
    case TokenKind::KwDelta: return "delta";
    case TokenKind::KwDigits: return "digits";
    case TokenKind::KwDo: return "do";
    case TokenKind::KwElse: return "else";
    case TokenKind::KwElsif: return "elsif";
    case TokenKind::KwEnd: return "end";
    case TokenKind::KwEntry: return "entry";
    case TokenKind::KwException: return "exception";
    case TokenKind::KwExit: return "exit";
    case TokenKind::KwFor: return "for";
    case TokenKind::KwFunction: return "function";
    case TokenKind::KwGeneric: return "generic";
    case TokenKind::KwGoto: return "goto";
    case TokenKind::KwIf: return "if";
    case TokenKind::KwIn: return "in";
    case TokenKind::KwIs: return "is";
    case TokenKind::KwLimited: return "limited";
    case TokenKind::KwLoop: return "loop";
    case TokenKind::KwMod: return "mod";
    case TokenKind::KwNew: return "new";
    case TokenKind::KwNot: return "not";
    case TokenKind::KwNull: return "null";
    case TokenKind::KwOf: return "of";
    case TokenKind::KwOr: return "or";
    case TokenKind::KwOthers: return "others";
    case TokenKind::KwOut: return "out";
    case TokenKind::KwOverriding: return "overriding";
    case TokenKind::KwPackage: return "package";
    case TokenKind::KwPragma: return "pragma";
    case TokenKind::KwPrivate: return "private";
    case TokenKind::KwProcedure: return "procedure";
    case TokenKind::KwRaise: return "raise";
    case TokenKind::KwRange: return "range";
    case TokenKind::KwRecord: return "record";
    case TokenKind::KwRem: return "rem";
    case TokenKind::KwRenames: return "renames";
    case TokenKind::KwReturn: return "return";
    case TokenKind::KwReverse: return "reverse";
    case TokenKind::KwSelect: return "select";
    case TokenKind::KwSeparate: return "separate";
    case TokenKind::KwSubtype: return "subtype";
    case TokenKind::KwTagged: return "tagged";
    case TokenKind::KwTask: return "task";
    case TokenKind::KwTerminate: return "terminate";
    case TokenKind::KwThen: return "then";
    case TokenKind::KwType: return "type";
    case TokenKind::KwUse: return "use";
    case TokenKind::KwWhen: return "when";
    case TokenKind::KwWhile: return "while";
    case TokenKind::KwWith: return "with";
    case TokenKind::KwXor: return "xor";
    case TokenKind::Ampersand: return "&";
    case TokenKind::Tick: return "'";
    case TokenKind::LeftParen: return "(";
    case TokenKind::RightParen: return ")";
    case TokenKind::Star: return "*";
    case TokenKind::Plus: return "+";
    case TokenKind::Comma: return ",";
    case TokenKind::Minus: return "-";
    case TokenKind::Dot: return ".";
    case TokenKind::Slash: return "/";
    case TokenKind::Colon: return ":";
    case TokenKind::Semicolon: return ";";
    case TokenKind::Less: return "<";
    case TokenKind::Equal: return "=";
    case TokenKind::Greater: return ">";
    case TokenKind::Bar: return "|";
    case TokenKind::Arrow: return "=>";
    case TokenKind::DoubleDot: return "..";
    case TokenKind::DoubleStar: return "**";
    case TokenKind::Assign: return ":=";
    case TokenKind::NotEqual: return "/=";
    case TokenKind::GreaterEqual: return ">=";
    case TokenKind::LessEqual: return "<=";
    case TokenKind::LeftLabel: return "<<";
    case TokenKind::RightLabel: return ">>";
    case TokenKind::Box: return "<>";
    }
    return "<unknown>";
}
