-- RM A.4.4 value-mapping subset. Max must be a static positive actual.
with Ada.Strings.Maps;
package Ada.Strings.Bounded is
    generic
        Max : Positive;
    package Generic_Bounded_Length is
        Max_Length : constant Positive := Max;
        subtype Length_Range is Natural range 0 .. Max_Length;
        type Bounded_String is private;
        Null_Bounded_String : constant Bounded_String;
        function Length (Source : Bounded_String) return Length_Range;
        function To_Bounded_String (Source : String; Drop : Truncation := Error) return Bounded_String;
        function To_String (Source : Bounded_String) return String;
        procedure Set_Bounded_String (Target : out Bounded_String; Source : String;
                                      Drop : Truncation := Error);
        function Append (Left : Bounded_String; Right : Bounded_String;
            Drop : Truncation := Error) return Bounded_String;
        function "&" (Left : Bounded_String; Right : Bounded_String) return Bounded_String;
        function Append (Left : Bounded_String; Right : String;
            Drop : Truncation := Error) return Bounded_String;
        function "&" (Left : Bounded_String; Right : String) return Bounded_String;
        function Append (Left : String; Right : Bounded_String;
            Drop : Truncation := Error) return Bounded_String;
        function "&" (Left : String; Right : Bounded_String) return Bounded_String;
        function Append (Left : Bounded_String; Right : Character;
            Drop : Truncation := Error) return Bounded_String;
        function "&" (Left : Bounded_String; Right : Character) return Bounded_String;
        function Append (Left : Character; Right : Bounded_String;
            Drop : Truncation := Error) return Bounded_String;
        function "&" (Left : Character; Right : Bounded_String) return Bounded_String;
        procedure Append (Source : in out Bounded_String; New_Item : Bounded_String;
            Drop : Truncation := Error);
        procedure Append (Source : in out Bounded_String; New_Item : String; Drop : Truncation := Error);
        procedure Append (Source : in out Bounded_String; New_Item : Character; Drop : Truncation := Error);
        function Element (Source : Bounded_String; Index : Positive) return Character;
        procedure Replace_Element (Source : in out Bounded_String; Index : Positive; By : Character);
        function Slice (Source : Bounded_String; Low : Positive; High : Natural) return String;
        function Bounded_Slice (Source : Bounded_String; Low : Positive;
            High : Natural) return Bounded_String;
        procedure Bounded_Slice (Source : Bounded_String; Target : out Bounded_String;
                                 Low : Positive; High : Natural);
        function "=" (Left : Bounded_String; Right : Bounded_String) return Boolean;
        function "=" (Left : Bounded_String; Right : String) return Boolean;
        function "=" (Left : String; Right : Bounded_String) return Boolean;
        function "<" (Left : Bounded_String; Right : Bounded_String) return Boolean;
        function "<" (Left : Bounded_String; Right : String) return Boolean;
        function "<" (Left : String; Right : Bounded_String) return Boolean;
        function "<=" (Left : Bounded_String; Right : Bounded_String) return Boolean;
        function "<=" (Left : Bounded_String; Right : String) return Boolean;
        function "<=" (Left : String; Right : Bounded_String) return Boolean;
        function ">" (Left : Bounded_String; Right : Bounded_String) return Boolean;
        function ">" (Left : Bounded_String; Right : String) return Boolean;
        function ">" (Left : String; Right : Bounded_String) return Boolean;
        function ">=" (Left : Bounded_String; Right : Bounded_String) return Boolean;
        function ">=" (Left : Bounded_String; Right : String) return Boolean;
        function ">=" (Left : String; Right : Bounded_String) return Boolean;
        function Index (Source : Bounded_String; Pattern : String; From : Positive;
            Going : Direction := Forward;
                        Mapping : Maps.Character_Mapping := Maps.Identity) return Natural;
        function Index (Source : Bounded_String; Pattern : String; Going : Direction := Forward;
                        Mapping : Maps.Character_Mapping := Maps.Identity) return Natural;
        function Index (Source : Bounded_String; Set : Maps.Character_Set; From : Positive;
                        Test : Membership := Inside; Going : Direction := Forward) return Natural;
        function Index (Source : Bounded_String; Set : Maps.Character_Set;
                        Test : Membership := Inside; Going : Direction := Forward) return Natural;
        function Index_Non_Blank (Source : Bounded_String; From : Positive;
            Going : Direction := Forward) return Natural;
        procedure Find_Token (Source : Bounded_String; Set : Maps.Character_Set; From : Positive;
                              Test : Membership; First : out Positive; Last : out Natural);
        function Index_Non_Blank (Source : Bounded_String; Going : Direction := Forward) return Natural;
        procedure Find_Token (Source : Bounded_String; Set : Maps.Character_Set;
                              Test : Membership; First : out Positive; Last : out Natural);
        function Count (Source : Bounded_String; Pattern : String;
            Mapping : Maps.Character_Mapping := Maps.Identity) return Natural;
        function Count (Source : Bounded_String; Set : Maps.Character_Set) return Natural;
        function Translate (Source : Bounded_String; Mapping : Maps.Character_Mapping) return Bounded_String;
        procedure Translate (Source : in out Bounded_String; Mapping : Maps.Character_Mapping);
        function Replace_Slice (Source : Bounded_String; Low : Positive; High : Natural; By : String;
            Drop : Truncation := Error) return Bounded_String;
        procedure Replace_Slice (Source : in out Bounded_String; Low : Positive; High : Natural; By : String;
            Drop : Truncation := Error);
        function Insert (Source : Bounded_String; Before : Positive; New_Item : String;
            Drop : Truncation := Error) return Bounded_String;
        procedure Insert (Source : in out Bounded_String; Before : Positive; New_Item : String;
            Drop : Truncation := Error);
        function Overwrite (Source : Bounded_String; Position : Positive; New_Item : String;
            Drop : Truncation := Error) return Bounded_String;
        procedure Overwrite (Source : in out Bounded_String; Position : Positive; New_Item : String;
            Drop : Truncation := Error);
        function Delete (Source : Bounded_String; From : Positive; Through : Natural) return Bounded_String;
        procedure Delete (Source : in out Bounded_String; From : Positive; Through : Natural);
        function Trim (Source : Bounded_String; Side : Trim_End) return Bounded_String;
        procedure Trim (Source : in out Bounded_String; Side : Trim_End);
        function Trim (Source : Bounded_String; Left, Right : Maps.Character_Set) return Bounded_String;
        procedure Trim (Source : in out Bounded_String; Left, Right : Maps.Character_Set);
        function Head (Source : Bounded_String; Count : Natural; Pad : Character := Space;
            Drop : Truncation := Error) return Bounded_String;
        procedure Head (Source : in out Bounded_String; Count : Natural; Pad : Character := Space;
            Drop : Truncation := Error);
        function Tail (Source : Bounded_String; Count : Natural; Pad : Character := Space;
            Drop : Truncation := Error) return Bounded_String;
        procedure Tail (Source : in out Bounded_String; Count : Natural; Pad : Character := Space;
            Drop : Truncation := Error);
        function Replicate (Count : Natural; Item : String; Drop : Truncation := Error) return Bounded_String;
        function Replicate (Count : Natural; Item : Character;
            Drop : Truncation := Error) return Bounded_String;
        function Replicate (Count : Natural; Item : Bounded_String;
            Drop : Truncation := Error) return Bounded_String;
        function "*" (Left : Natural; Right : Character) return Bounded_String;
        function "*" (Left : Natural; Right : String) return Bounded_String;
        function "*" (Left : Natural; Right : Bounded_String) return Bounded_String;
    private
        type Bounded_String is record
            length : Length_Range := 0;
            data : String (1 .. Max_Length) := (others => Character'Val (0));
        end record;
        Null_Bounded_String : constant Bounded_String :=
            (length => 0, data => (others => Character'Val (0)));
    end Generic_Bounded_Length;
end Ada.Strings.Bounded;
