-- RM A.4.3 value-mapping overloads; mapping callbacks are not supported.
with Ada.Strings.Maps;
package Ada.Strings.Fixed is
    procedure Move (Source : String; Target : out String; Drop : Truncation := Error;
                   Justify : Alignment := Left; Pad : Character := Space);
    function Index (Source, Pattern : String; From : Positive;
                    Going : Direction := Forward; Mapping : Maps.Character_Mapping := Maps.Identity) return Natural;
    function Index (Source, Pattern : String; Going : Direction := Forward;
                    Mapping : Maps.Character_Mapping := Maps.Identity) return Natural;
    function Index (Source : String; Set : Maps.Character_Set; From : Positive;
                    Test : Membership := Inside; Going : Direction := Forward) return Natural;
    function Index (Source : String; Set : Maps.Character_Set;
                    Test : Membership := Inside; Going : Direction := Forward) return Natural;
    function Index_Non_Blank (Source : String; From : Positive; Going : Direction := Forward) return Natural;
    function Index_Non_Blank (Source : String; Going : Direction := Forward) return Natural;
    function Count (Source, Pattern : String;
                    Mapping : Maps.Character_Mapping := Maps.Identity) return Natural;
    function Count (Source : String; Set : Maps.Character_Set) return Natural;
    procedure Find_Token (Source : String; Set : Maps.Character_Set; From : Positive;
                          Test : Membership; First : out Positive; Last : out Natural);
    procedure Find_Token (Source : String; Set : Maps.Character_Set;
                          Test : Membership; First : out Positive; Last : out Natural);
    function Translate (Source : String; Mapping : Maps.Character_Mapping) return String;
    procedure Translate (Source : in out String; Mapping : Maps.Character_Mapping);
    function Insert (Source : String; Before : Positive; New_Item : String) return String;
    function Replace_Slice (Source : String; Low : Positive; High : Natural; By : String) return String;
    function Overwrite (Source : String; Position : Positive; New_Item : String) return String;
    function Delete (Source : String; From : Positive; Through : Natural) return String;
    function Trim (Source : String; Left, Right : Maps.Character_Set) return String;
    function Trim (Source : String; Side : Trim_End) return String;
    function Head (Source : String; Count : Natural; Pad : Character := Space) return String;
    function Tail (Source : String; Count : Natural; Pad : Character := Space) return String;
    procedure Insert (Source : in out String; Before : Positive; New_Item : String;
                      Drop : Truncation := Error);
    procedure Replace_Slice (Source : in out String; Low : Positive; High : Natural; By : String;
                      Drop : Truncation := Error; Justify : Alignment := Left; Pad : Character := Space);
    procedure Overwrite (Source : in out String; Position : Positive; New_Item : String;
                      Drop : Truncation := Right);
    procedure Delete (Source : in out String; From : Positive; Through : Natural;
                      Justify : Alignment := Left; Pad : Character := Space);
    procedure Trim (Source : in out String; Side : Trim_End;
                      Justify : Alignment := Left; Pad : Character := Space);
    procedure Trim (Source : in out String; Left, Right : Maps.Character_Set;
                      Justify : Alignment := Strings.Left; Pad : Character := Space);
    procedure Head (Source : in out String; Count : Natural;
                      Justify : Alignment := Left; Pad : Character := Space);
    procedure Tail (Source : in out String; Count : Natural;
                      Justify : Alignment := Left; Pad : Character := Space);
    function "*" (Left : Natural; Right : Character) return String;
    function "*" (Left : Natural; Right : String) return String;
end Ada.Strings.Fixed;
